# -*- coding: utf-8 -*-
"""Lap1-Introduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sWhWuiJIHilEmOZ2dA6ZMlZDSNhJLF3A
"""

###Data types

1 + 1

1 * 3

1 / 2

2 ** 4

4 % 2

5 % 2

(2 + 3) * (5 + 5)

name_of_var = 2
x = 2
y = 3
z = x + y
z

'single quotes'

"double quotes"

"wrap lot's of other quotes"

x = 'hello'
x

print(x)

num = 12
name = 'Sam'
print('My name is: {one}, and my name is: {two}'.format(one=num, two= name))

print('My name is: {}, and my name is: {}'.format(num,name))

[1,2,3]

['hi',1,[1,2]]

my_list = ['a', 'b', 'c']
my_list.append('d')
my_list

my_list[0]

my_list[1]

my_list[1:]

my_list[:1]

my_list[0] = 'New'
my_list

nest = [1,2,3,[4,5,['target']]]
nest[3]

nest[3][2]

nest[3][2][0]

d = {'key1':'item1','key2':'item2'}
d

d[ 'key1' ]

True

False

t = (1,2,3)
t[0]

lst=list(t)
lst[0]='NEW'
t=tuple(lst)
t

{1,2,3}

{1,2,3,1,2,1,2,3,3,3,2,2,2,1,1,2}

1 > 2

1 < 2

1 >= 1

1 <= 4

1 == 1

'hi' == 'bye'

(1 >2) and (2 <3)

(1 >2) or (2 <3)

(1 == 2) or (2 == 3) or (4 == 4)

if 1 < 2:
  print('Yep1')

if 1 < 2:
  print('Yep1')

if 1 < 2:
    print('first')
else:
    print('last')

if 1 > 2:
    print('first')
else:
    print('last')

if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('last')

seq = [1,2,3,4,5]
for item in  seq:
    print(item)

for item in  seq:
    print('Yep')

for jelly in seq:
    print(jelly+jelly)

i = 1
while i<5:
    print('i is: {}'.format(i))
    i = i+1

range(5)

for i in range(5):
    print(i)

list(range(5))

x = [1,2,3,4]
out = []
for item in x:
    out.append(item**2)
print(out)

[item**2 for item in x]

def my_func(paraml='default'):
  """
  Docstring goes here.
  """
  print(paraml)
my_func

my_func()

my_func('new param')

my_func(paraml='new param')

def square(x):
    return x**2
out = square(2)
print(out)

def times2(var):
  return var*2
times2(2)

var = lambda var: var**2
var(2)

seq = [1,2,3,4,5]
map(times2,seq)

list(map(times2,seq))

list(map(lambda var: var*2,seq))

filter(lambda item: item%2 == 0,seq)

list(filter(lambda item:item%2 == 0,seq))

st = 'hello my name is Sam'
st.lower()

st.upper()

st.split()

tweet = 'Go Sportal #Sports'
tweet.split('#')

tweet.split('#')[1]

d

d.keys()

d.items()

lst = [1,2,3]
lst.pop()

lst

'x' in [1,2,3]

'x' in ['x','y','z']

### Python basics - Exercises

7 ** 4

s = "Hi there Sam!"
s.split()

planet = "Earth"
diameter = 12742
print('The diameter of {} is {} kilometers.'.format(planet,diameter))

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
lst[3][1][2][0]

d = {'k1':[1,2,3,{'stricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['stricky'][3]['target'][3]

def domainGet(inp):
  return inp.split('@')[1]
domainGet('user@domain.com')

def findDog(inp):
    return 'dog' in inp.lower().split()
findDog('Is there a dog here')

def countDog(inp):
    dog = 0
    for x in inp.lower().split():
        if x == 'dog':
            dog += 1
    return dog
countDog('This dog runs faster than the dog dude1')

seq = ['soup','dog','salad','cat','great']
['soup','salad']

def caught_speeding(speed, is_birthday):
    if is_birthday:
        speed = speed - 5
    if speed > 80:
        return 'Big Ticket'
    elif speed > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
caught_speeding(81,True)

caught_speeding(81,False)



